import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageContainer from "@/components/PageContainer";
// import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-between min-h-screen">
          <PageContainer>
            <Header />
          </PageContainer>
          {/* flex grow = pour que les composant prennent le maximum de place sur l'écran */}
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
